# Generated by Django 5.1.3 on 2026-02-25 01:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_number', models.CharField(max_length=100, unique=True, verbose_name='Consignment Number')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking Number')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], max_length=50, verbose_name='State')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='Ship Date')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Estimated Delivery')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Consignment',
                'verbose_name_plural': 'Consignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('address_change', 'Address Change'), ('info_change', 'Info Change'), ('issue', 'Issue/Problem'), ('special_request', 'Special Request')], default='general', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20, verbose_name='Priority')),
                ('is_visible_to_customer', models.BooleanField(default=False, verbose_name='Visible to Customer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Consignment Note',
                'verbose_name_plural': 'Consignment Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('countries', models.JSONField(default=list, verbose_name='Countries')),
                ('postal_code_patterns', models.JSONField(blank=True, default=list, verbose_name='Postal Code Patterns')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FreightService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per kg')),
                ('estimated_days_min', models.PositiveIntegerField(default=1, verbose_name='Est. Days (Min)')),
                ('estimated_days_max', models.PositiveIntegerField(default=7, verbose_name='Est. Days (Max)')),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min Weight')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Weight')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Billing configuration, e.g. mapping to products.', verbose_name='Configuration')),
                ('transport_type', models.CharField(blank=True, choices=[('air', 'Air'), ('sea', 'Sea'), ('road', 'Road'), ('rail', 'Rail'), ('other', 'Other')], max_length=50, verbose_name='Transport Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Freight Service',
                'verbose_name_plural': 'Freight Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FreightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('manifest', 'Manifest'), ('consignment', 'Consignment'), ('package', 'Package')], max_length=50, verbose_name='Type')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], max_length=50, verbose_name='State')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('send_message', models.BooleanField(default=False, verbose_name='Send Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Freight Status',
                'verbose_name_plural': 'Freight Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=100, unique=True, verbose_name='Manifest Number')),
                ('manifest_date', models.DateField(verbose_name='Manifest Date')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pickup Date')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], max_length=50, verbose_name='State')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Manifest',
                'verbose_name_plural': 'Manifests',
                'ordering': ['-manifest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(max_length=100, verbose_name='Package Number')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight (kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height (cm)')),
                ('pieces', models.IntegerField(blank=True, default=1, null=True, verbose_name='Pieces')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], max_length=50, verbose_name='State')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['package_number'],
            },
        ),
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Length (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Width (cm)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Height (cm)')),
                ('tare_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Empty box weight', max_digits=10, verbose_name='Tare Weight (kg)')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight capacity', max_digits=10, null=True, verbose_name='Max Weight (kg)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Package Template',
                'verbose_name_plural': 'Package Templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Changed'), ('attribute_change', 'Attribute Changed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('exception', 'Exception'), ('returned', 'Returned'), ('note_added', 'Note Added'), ('customer_changed', 'Customer Changed')], max_length=50, verbose_name='Event Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('is_public', models.BooleanField(default=False, verbose_name='Publicly Visible')),
                ('event_time', models.DateTimeField(verbose_name='Event Time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('carrier_type', models.CharField(blank=True, help_text='Plugin identifier. Leave empty for manual/custom carriers.', max_length=50, verbose_name='Carrier Type')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('test_config', models.JSONField(blank=True, default=dict, verbose_name='Test Configuration')),
                ('is_test_mode', models.BooleanField(default=False, verbose_name='Test Mode')),
                ('tracking_url_template', models.CharField(blank=True, max_length=500, verbose_name='Tracking URL Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'ordering': ['name'],
            },
        ),
    ]
