# Generated by Django 5.1.3 on 2026-02-25 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('delivery', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='orders',
            field=models.ManyToManyField(related_name='consignments', to='shop.order'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='recipient_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_consignments', to='common.address'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='sender_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_consignments', to='common.address'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='consignmentnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignmentnote',
            name='consignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_notes', to='delivery.consignment'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='freightservice',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='delivery.carrier'),
        ),
        migrations.AddField(
            model_name='freightservice',
            name='delivery_zones',
            field=models.ManyToManyField(blank=True, related_name='freight_services', to='delivery.deliveryzone', verbose_name='Delivery Zones'),
        ),
        migrations.AddField(
            model_name='freightservice',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_services', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='delivery.freightservice'),
        ),
        migrations.AddField(
            model_name='freightstatus',
            name='mapped_consignment_status',
            field=models.ForeignKey(blank=True, help_text='For a package status, the corresponding consignment FreightStatus (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_statuses_mapped_to_this_consignment_status', to='delivery.freightstatus', verbose_name='Mapped Consignment Status'),
        ),
        migrations.AddField(
            model_name='freightstatus',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_statuses', to='common.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='delivery.freightstatus'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='delivery.carrier'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='delivery.freightstatus'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to='delivery.manifest'),
        ),
        migrations.AddField(
            model_name='package',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='delivery.consignment'),
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Shop order this package belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shop.order'),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='delivery.freightstatus'),
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_templates', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='package',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Package template used for dimensions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='delivery.packagetemplate'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_types', to='common.workspace', verbose_name='Workspace'),
        ),
        migrations.AddField(
            model_name='package',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='delivery.storagelocation', verbose_name='Storage Location'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackingevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='delivery.warehouse'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_manifests', to='delivery.warehouse', verbose_name='Destination Warehouse'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='delivery.warehouse', verbose_name='Origin Warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='carrier',
            unique_together={('workspace', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryzone',
            unique_together={('workspace', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='freightstatus',
            unique_together={('workspace', 'code')},
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['workspace', '-created_at'], name='delivery_co_workspa_189ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignment_number'], name='delivery_co_consign_578209_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['tracking_number'], name='delivery_co_trackin_8ba3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['status'], name='delivery_co_status__d3c550_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packagetemplate',
            unique_together={('workspace', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('workspace', 'code')},
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['content_type', 'object_id', '-event_time'], name='delivery_tr_content_7c8d88_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['workspace', '-event_time'], name='delivery_tr_workspa_2e2aea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('workspace', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['workspace', '-manifest_date'], name='delivery_ma_workspa_09701c_idx'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['manifest_number'], name='delivery_ma_manifes_ae47ae_idx'),
        ),
    ]
