# Generated by Django 6.0.6 on 2026-06-11 14:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'Carrier', 'verbose_name_plural': 'Carriers'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelManagers(
            name='carrier',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
