# Generated by Django 6.0.6 on 2026-08-30 01:16

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_settings_country'),
        ('delivery', '0003_alter_carrier_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('instructions', models.TextField(blank=True, help_text='Opening hours, which door, where to park — shown to the shopper.', verbose_name='Pickup Instructions')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Charged on the order's shipping_cost line, which is the delivery charge line.", max_digits=10, verbose_name='Pickup Fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Where the stock collected here comes from, if it is one of our own.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='delivery.warehouse')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Pickup Point',
                'verbose_name_plural': 'Pickup Points',
                'ordering': ['sort_order', 'name'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='delivery_pi_workspa_f39f85_idx')],
                'unique_together': {('workspace', 'code')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
