# Generated by Django 6.0.6 on 2026-09-17 09:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0018_workspace_extension_archive_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPortalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('registration_enabled', models.BooleanField(default=False, verbose_name='Registration enabled')),
                ('provisioning_extensions', models.JSONField(blank=True, default=list, verbose_name='Provisioning extensions')),
                ('default_theme', models.CharField(blank=True, max_length=64, verbose_name='Default theme')),
                ('default_plan', models.CharField(blank=True, max_length=64, verbose_name='Default plan')),
                ('default_country', models.CharField(blank=True, max_length=2, verbose_name='Default country')),
                ('default_currency', models.CharField(blank=True, max_length=3, verbose_name='Default currency')),
                ('default_language', models.CharField(blank=True, max_length=16, verbose_name='Default language')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_portal_profile', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Brand portal profile',
                'verbose_name_plural': 'Brand portal profiles',
                'ordering': ['workspace_id'],
            },
        ),
        migrations.CreateModel(
            name='BrandPortalProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Idempotency key')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Profile snapshot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='Status')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='Error code')),
                ('error_detail', models.TextField(blank=True, verbose_name='Error detail')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('portal_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_portal_provisionings', to='common.workspace', verbose_name='Portal workspace')),
                ('target_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_portal_sources', to='common.workspace', verbose_name='Target workspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_portal_provisionings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Brand portal provisioning',
                'verbose_name_plural': 'Brand portal provisionings',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['portal_workspace', 'status', '-created_at'], name='brand_portal_status_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('portal_workspace', 'idempotency_key'), name='brand_portal_workspace_idempotency_uniq')],
            },
        ),
    ]
