# Generated by Django 5.1.3 on 2026-02-25 01:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_type', models.CharField(choices=[('notification', 'Notification'), ('message', 'Direct Message'), ('system', 'System Message'), ('announcement', 'Announcement')], default='notification', max_length=20, verbose_name='Type')),
                ('action_url', models.URLField(blank=True, verbose_name='Action URL')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='Action Label')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False, verbose_name='Send Email')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Send SMS')),
                ('send_push', models.BooleanField(default=False, verbose_name='Send Push')),
                ('send_email_at', models.DateTimeField(blank=True, null=True, verbose_name='Send Email At')),
                ('send_sms_at', models.DateTimeField(blank=True, null=True, verbose_name='Send SMS At')),
                ('send_push_at', models.DateTimeField(blank=True, null=True, verbose_name='Send Push At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='inbox.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='common.customer')),
            ],
            options={
                'verbose_name': 'Message Recipient',
                'verbose_name_plural': 'Message Recipients',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('event', models.CharField(max_length=50, verbose_name='Event')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email Enabled')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, verbose_name='Email Body')),
                ('email_html_body', models.TextField(blank=True, verbose_name='Email HTML Body')),
                ('app_message_enabled', models.BooleanField(default=False, verbose_name='App Message Enabled')),
                ('app_message_title', models.CharField(blank=True, max_length=255, verbose_name='App Message Title')),
                ('app_message_body', models.TextField(blank=True, verbose_name='App Message Body')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Enabled')),
                ('sms_body', models.TextField(blank=True, max_length=160, verbose_name='SMS Body')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Push Enabled')),
                ('push_title', models.CharField(blank=True, max_length=100, verbose_name='Push Title')),
                ('push_body', models.CharField(blank=True, max_length=255, verbose_name='Push Body')),
                ('available_variables', models.JSONField(blank=True, default=dict, verbose_name='Available Variables')),
                ('language', models.CharField(max_length=10, verbose_name='Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=160, verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='Provider')),
                ('provider_id', models.CharField(blank=True, max_length=100, verbose_name='Provider ID')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Provider Response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='common.customer')),
                ('message_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='inbox.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='common.workspace')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['workspace', '-created_at'], name='inbox_messa_workspa_e6ef43_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['recipient', 'is_read'], name='inbox_messa_recipie_57f80b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['recipient', 'delivered_at'], name='inbox_messa_recipie_a1cefd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('workspace', 'code', 'language')},
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['workspace', '-created_at'], name='inbox_smsme_workspa_6ab7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['customer', '-created_at'], name='inbox_smsme_custome_2426b0_idx'),
        ),
    ]
