# Generated by Django 5.1.3 on 2026-02-10 09:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Campaign Group',
                'verbose_name_plural': 'Campaign Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('qualified', 'Qualified'), ('coupon_issued', 'Coupon Issued'), ('redeemed', 'Redeemed')], default='registered', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Campaign Participation',
                'verbose_name_plural': 'Campaign Participations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='Tracking Code')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Channel Link',
                'verbose_name_plural': 'Channel Links',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit')),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit per Customer')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Times Used')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('free_shipping', 'Free Shipping'), ('buy_x_get_y', 'Buy X Get Y'), ('other', 'Other')], max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('apply_to', models.CharField(choices=[('order', 'Entire Order'), ('products', 'Specific Products'), ('categories', 'Specific Categories'), ('other', 'Other')], default='order', max_length=20, verbose_name='Apply To')),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Purchase')),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Discount')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('prerequisite_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prerequisite Quantity')),
                ('prerequisite_product_ids', models.JSONField(blank=True, default=list, verbose_name='Prerequisite Product IDs')),
                ('entitled_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Entitled Quantity')),
                ('entitled_product_ids', models.JSONField(blank=True, default=list, verbose_name='Entitled Product IDs')),
                ('allocation_method', models.CharField(choices=[('each', 'Each'), ('across', 'Across')], default='each', max_length=20, verbose_name='Allocation Method')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('display_label', models.CharField(blank=True, max_length=255, verbose_name='Display Label')),
                ('promo_display_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Promo Display Order')),
                ('is_group_buy', models.BooleanField(default=False, verbose_name='Is Group Buy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Value')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Expires At')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='Referer')),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Clicked At')),
            ],
            options={
                'verbose_name': 'Link Click',
                'verbose_name_plural': 'Link Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, unique=True, verbose_name='Referral Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rewarded', 'Rewarded')], default='pending', max_length=20, verbose_name='Status')),
                ('referrer_rewarded', models.BooleanField(default=False, verbose_name='Referrer Rewarded')),
                ('referee_rewarded', models.BooleanField(default=False, verbose_name='Referee Rewarded')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('referrer_reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Referrer Reward')),
                ('referee_reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Referee Reward')),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Purchase')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Referral Program',
                'verbose_name_plural': 'Referral Programs',
            },
        ),
        migrations.CreateModel(
            name='StampRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('stamp', 'Stamp'), ('redemption', 'Redemption')], max_length=20, verbose_name='Record Type')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='Period Start')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Period End')),
                ('week_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Week Index')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Stamp Record',
                'verbose_name_plural': 'Stamp Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission Rate %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_partners', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Affiliate Partner',
                'verbose_name_plural': 'Affiliate Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('social', 'Social Media'), ('affiliate', 'Affiliate'), ('other', 'Other')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('requires_participation', models.BooleanField(default=False, verbose_name='Requires Participation')),
                ('min_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min Participants')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Participants')),
                ('promo_display_type', models.CharField(blank=True, max_length=50, verbose_name='Promo Display Type')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='Conversions')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Revenue')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='marketing.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Analytics',
                'verbose_name_plural': 'Campaign Analytics',
            },
        ),
        migrations.CreateModel(
            name='CampaignDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('slide', 'Slide'), ('category_entry', 'Category Entry'), ('featured', 'Featured')], max_length=30, verbose_name='Display Type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/display/', verbose_name='Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Link URL')),
                ('link_target', models.CharField(blank=True, max_length=10, verbose_name='Link Target')),
                ('rules', models.JSONField(blank=True, default=list, help_text='Same as ProductCategory.rules: [{"column":"price","relation":"greater_than","condition":"100"}, {"column":"category_id","relation":"equals","condition":"5"}]', verbose_name='Rules')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='marketing.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Display',
                'verbose_name_plural': 'Campaign Displays',
                'ordering': ['order', 'id'],
            },
        ),
    ]
