# Generated by Django 5.1.3 on 2026-02-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('finance', '0002_initial'),
        ('marketing', '0001_initial'),
        ('shop', '0001_initial'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndisplay',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.post'),
        ),
        migrations.AddField(
            model_name='campaigndisplay',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Required when campaign is not set; otherwise derived from campaign.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_displays', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_groups', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.campaigngroup'),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='common.customer'),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.order'),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='channel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='channellink',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='channellink',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='marketing.channel'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='boost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='marketing.campaignparticipation'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='discount_rules', to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='discount_rules', to='shop.product'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='marketing.discountrule'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='common.customer'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='common.customer'),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='marketing.channellink'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='common.customer'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='common.customer'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_programs', to='common.workspace'),
        ),
        migrations.AddField(
            model_name='referral',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='marketing.referralprogram'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_records', to='marketing.campaign'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_records', to='common.customer'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.order'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.orderitem'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='reward_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketing.coupon'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='reward_gift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketing.giftcard'),
        ),
        migrations.AddField(
            model_name='stamprecord',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_records', to='common.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('workspace', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('workspace', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='giftcard',
            unique_together={('workspace', 'code')},
        ),
    ]
