# Generated by Django 6.0.6 on 2026-06-11 14:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'base_manager_name': 'all_objects', 'ordering': ['-start_date'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='discountrule',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'Discount Rule', 'verbose_name_plural': 'Discount Rules'},
        ),
        migrations.AlterModelOptions(
            name='giftcard',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Gift Card', 'verbose_name_plural': 'Gift Cards'},
        ),
        migrations.AlterModelManagers(
            name='campaign',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='coupon',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='discountrule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='giftcard',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
