# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndisplay',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link URL'),
        ),
    ]
