# Generated by Django 6.0.6 on 2026-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_campaign_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndisplay',
            name='context',
            field=models.CharField(blank=True, choices=[('', 'All pages'), ('home', 'Home page'), ('category', 'Category page')], default='', help_text='Storefront page this display belongs to. Leave blank to show it on every page that asks.', max_length=30, verbose_name='Context'),
        ),
    ]
