# Generated by Django 5.1.3 on 2026-02-25 01:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Decimal Places')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Discount multiplier (1.00 = 100%, 0.80 = 80%)', max_digits=5, verbose_name='Discount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount calculated based on tax_type and subtotal', max_digits=10, verbose_name='Tax Amount')),
                ('tax_type', models.CharField(choices=[('default', 'Use Workspace Default Tax Rate'), ('no_tax', 'No Tax'), ('zero_gst', 'Zero Tax')], default='default', help_text='Tax treatment for this item', max_length=20, verbose_name='Tax Type')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Payment Number')),
                ('gateway_display_name', models.CharField(blank=True, help_text='Snapshot of gateway name when payment was made; kept after gateway is removed.', max_length=255, verbose_name='Gateway (at payment time)')),
                ('gateway_type', models.CharField(blank=True, help_text='Snapshot of gateway type (e.g. stripe, custom); kept after gateway is removed.', max_length=20, verbose_name='Gateway type (at payment time)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway Transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('bank_transfer', 'Bank Transfer'), ('custom', 'Custom')], max_length=20, verbose_name='Gateway Type')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('test_config', models.JSONField(default=dict, verbose_name='Test Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_test_mode', models.BooleanField(default=False, verbose_name='Test Mode')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Account'), ('wallet', 'Digital Wallet')], max_length=20, verbose_name='Method Type')),
                ('gateway_token', models.CharField(help_text='Tokenized reference from payment gateway. Never store raw card data.', max_length=255, verbose_name='Gateway Token')),
                ('cardholder_name', models.CharField(blank=True, help_text='Name on the card', max_length=255, verbose_name='Cardholder Name')),
                ('card_brand', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('jcb', 'JCB'), ('diners', 'Diners Club'), ('unionpay', 'UnionPay'), ('unknown', 'Unknown')], help_text='Card brand (Visa, MasterCard, etc.)', max_length=20, verbose_name='Card Brand')),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card number for display', max_length=4, verbose_name='Last 4 Digits')),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, help_text='Card expiration month (1-12)', null=True, verbose_name='Expiration Month')),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, help_text='Card expiration year (YYYY)', null=True, verbose_name='Expiration Year')),
                ('expires_at', models.DateField(blank=True, help_text='Deprecated: Use card_exp_month and card_exp_year instead', null=True, verbose_name='Expires At')),
                ('display_info', models.CharField(blank=True, help_text='Human-readable payment method description', max_length=255, verbose_name='Display Info')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default payment method for customer', verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway Refund ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate %')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('credit', 'Credit'), ('debit', 'Debit'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Balance')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Credit Limit')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='Cycle Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('next_billing_date', models.DateField(verbose_name='Next Billing Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='common.customer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(max_length=50, unique=True, verbose_name='Statement Number')),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Previous Balance')),
                ('charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Charges')),
                ('payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Payments')),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Adjustments')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Current Balance')),
                ('statement_date', models.DateField(verbose_name='Statement Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='finance.billingcycle')),
            ],
            options={
                'verbose_name': 'Billing Statement',
                'verbose_name_plural': 'Billing Statements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/', verbose_name='Logo')),
                ('is_default', models.BooleanField(default=False, help_text='Only one brand can be default per workspace', verbose_name='Is Default')),
                ('tax_id', models.CharField(blank=True, help_text='Business registration number or tax ID', max_length=100, verbose_name='Tax ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration Number')),
                ('invoice_note', models.TextField(blank=True, help_text='Payment instructions or bank details to display on invoices', verbose_name='Invoice Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='common.address', verbose_name='Address')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Rate')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='finance.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='finance.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Financial code, e.g., '001', '002'", max_length=50, verbose_name='Code')),
                ('name', models.CharField(help_text="Code name, e.g., 'Software Service', 'Overseas Software Service'", max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this financial code', verbose_name='Description')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Default unit price for items using this financial code', max_digits=10, null=True, verbose_name='Unit Price')),
                ('unit', models.CharField(blank=True, help_text="Unit of measurement, e.g., 'hour', 'day', 'piece', 'item'", max_length=50, verbose_name='Unit')),
                ('tax_type', models.CharField(choices=[('default', 'Use Workspace Default Tax Rate'), ('no_tax', 'No Tax'), ('zero_gst', 'Zero Tax')], default='default', help_text='Tax treatment for items using this code', max_length=20, verbose_name='Tax Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_codes', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Financial Code',
                'verbose_name_plural': 'Financial Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Tax')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(blank=True, help_text='Business name/brand used for this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.brand', verbose_name='Brand')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='common.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
