# Generated by Django 5.1.3 on 2026-03-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_settings_default_currency'),
        ('finance', '0004_transaction_wallet_fields_withdrawalrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_wallet__4bc174_idx',
            old_name='finance_tra_wallet__idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_source__6b9cc4_idx',
            old_name='finance_tra_source__idx',
        ),
        migrations.RenameIndex(
            model_name='wallet',
            new_name='finance_wal_workspa_fcef21_idx',
            old_name='finance_wal_workspa_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='finance_wit_wallet__369c39_idx',
            old_name='finance_wit_wallet__idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('credit', 'Credit'), ('debit', 'Debit'), ('adjustment', 'Adjustment'), ('topup', 'Top-up'), ('withdrawal', 'Withdrawal'), ('reward', 'Reward')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='common.workspace'),
        ),
    ]
