# Generated by Django 6.0.6 on 2026-06-11 14:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_finance_tra_wallet__idx_finance_tra_wallet__4bc174_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'all_objects', 'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wallet',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
