# Generated by Django 6.0.6 on 2026-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay'), ('bank_transfer', 'Bank Transfer'), ('pay_in_store', 'Pay in Store'), ('custom', 'Custom')], max_length=20, verbose_name='Gateway Type'),
        ),
    ]
