# Generated by Django 6.0.6 on 2026-09-12 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_settings_enabled_currencies'),
        ('finance', '0007_paymentgateway_pay_in_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=20, verbose_name='Invoice Prefix')),
                ('default_due_days', models.PositiveIntegerField(default=30, verbose_name='Default Due Days')),
                ('default_footer', models.TextField(blank=True, help_text='Printed at the bottom of every invoice, e.g. payment terms', verbose_name='Default Footer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
    ]
