# Generated by Django 6.0.6 on 2026-09-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Make a partially applied MySQL migration safe to retry."""

    def _column_exists(self, schema_editor, model):
        with schema_editor.connection.cursor() as cursor:
            columns = schema_editor.connection.introspection.get_table_description(
                cursor, model._meta.db_table
            )
        return self.name in {column.name for column in columns}

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if not self._column_exists(schema_editor, model):
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        if self._column_exists(schema_editor, model):
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_refund_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddFieldIfMissing(
            model_name='exchangerate',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Who entered the rate, for one that was not read from the feed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Entered By'),
        ),
        AddFieldIfMissing(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('feed', 'Reference Feed'), ('manual', 'Entered By Hand')], default='feed', max_length=16, verbose_name='Source'),
        ),
    ]
