# Generated by Django 6.0.6 on 2026-09-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_refund_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Who entered the rate, for one that was not read from the feed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Entered By'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('feed', 'Reference Feed'), ('manual', 'Entered By Hand')], default='feed', max_length=16, verbose_name='Source'),
        ),
    ]
