# Generated by Hermes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(
                choices=[('shipping', 'Shipping'), ('pickup', 'Pickup')],
                default='shipping',
                max_length=20,
                verbose_name='Fulfillment Method',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name='billing_orders',
                to='common.address',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name='shipping_orders',
                to='common.address',
            ),
        ),
    ]
