# Generated by Django 6.0.6 on 2026-08-23 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_settings_country'),
        ('shop', '0005_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Notified')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notified At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_notifications', to='common.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='shop.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='shop.productvariant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Stock Notification',
                'verbose_name_plural': 'Stock Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'product', 'is_notified'], name='shop_stockn_workspa_9e0977_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('workspace', 'product', 'variant', 'email'), name='uniq_stock_notification_variant'), models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('workspace', 'product', 'email'), name='uniq_stock_notification_product')],
            },
        ),
    ]
