# Generated by Django 6.0.6 on 2026-08-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_pickuppoint'),
        ('shop', '0006_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, help_text='Whatever the customer quotes on collection: a locker PIN handed to us by the provider, or a code we generated for the counter to check. One field on purpose — shops use one or the other, never both.', max_length=64, verbose_name='Pickup Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, help_text="Where the customer collects this order. Required when fulfillment_method is 'pickup'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.pickuppoint'),
        ),
    ]
