# Generated by Django 6.0.6 on 2026-08-30 02:17

"""Give collection orders their own status, and move the existing ones onto it.

A collection order waiting at the counter has always been recorded as
`shipped`, because that was the only word available. Four screens relabelled it
on the way out, and anything reading the database directly saw a parcel in
transit that had never left the building.

Nothing is being reclassified here: those orders were ready for collection, and
`ready_for_pickup` is what they were all along.
"""

from django.db import migrations, models


def name_collection_orders(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    Order.objects.filter(fulfillment_method='pickup', status='shipped').update(
        status='ready_for_pickup'
    )


def back_to_shipped(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    Order.objects.filter(status='ready_for_pickup').update(status='shipped')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_pickup_code_order_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(name_collection_orders, back_to_shipped),
    ]
