# Generated by Django 6.0.6 on 2026-09-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_seed_platform_social_auth_from_env'),
        ('delivery', '0004_pickuppoint'),
        ('marketing', '0005_campaigndisplay_context_home_backfill'),
        ('shop', '0008_order_ready_for_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, verbose_name='Order Number'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('workspace', 'order_number'), name='shop_order_workspace_order_number_uniq'),
        ),
    ]
