# Generated by Django 6.0.6 on 2026-09-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_number_unique_per_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='return',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refunded At'),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_number',
            field=models.CharField(max_length=50, verbose_name='Return Number'),
        ),
    ]
