# Generated by Django 6.0.6 on 2026-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_return_number_per_workspace_and_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="What this plan sells, for a deployment selling to its workspaces: the extension's key, or empty for the base plan.", max_length=64, verbose_name='Code'),
        ),
    ]
