# Generated by Django 5.1.3 on 2026-02-10 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_categories', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Feedback Category',
                'verbose_name_plural': 'Feedback Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='support.knowledgecategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_categories', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('workspace', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('members', models.ManyToManyField(related_name='support_teams', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_teams', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Support Team',
                'verbose_name_plural': 'Support Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='Ticket Number')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending Customer'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('web', 'Web Form'), ('phone', 'Phone'), ('chat', 'Live Chat'), ('social', 'Social Media')], default='web', max_length=20, verbose_name='Channel')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='First Response At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='common.customer')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='shop.order')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.supportteam')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='Staff Reply')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Internal Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned At')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_from', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Assignment',
                'verbose_name_plural': 'Ticket Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketcategory'),
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Level')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color')),
                ('response_time_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Response Time (hours)')),
                ('resolution_time_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Resolution Time (hours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_priorities', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Ticket Priority',
                'verbose_name_plural': 'Ticket Priorities',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.ticketpriority'),
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('first_response_hours', models.PositiveIntegerField(verbose_name='First Response (hours)')),
                ('resolution_hours', models.PositiveIntegerField(verbose_name='Resolution (hours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='common.workspace')),
                ('priorities', models.ManyToManyField(related_name='slas', to='support.ticketpriority')),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Ticket Tag',
                'verbose_name_plural': 'Ticket Tags',
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='support.tickettag'),
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='support.ticketcategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_templates', to='common.workspace')),
            ],
            options={
                'verbose_name': 'Ticket Template',
                'verbose_name_plural': 'Ticket Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('praise', 'Praise'), ('other', 'Other')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='Page URL')),
                ('screenshot', models.ImageField(blank=True, upload_to='feedback/', verbose_name='Screenshot')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Device')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='support.feedbackcategory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='common.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reviewed', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='common.workspace')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful Count')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='Not Helpful Count')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('language', models.CharField(max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to='common.workspace')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='support.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'slug', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['workspace', '-created_at'], name='support_sup_workspa_293e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer', '-created_at'], name='support_sup_custome_6d3c97_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='support_sup_ticket__4a7d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='support_sup_status_c35d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to'], name='support_sup_assigne_53b075_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['workspace', '-created_at'], name='support_use_workspa_349a62_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['feedback_type'], name='support_use_feedbac_a83fce_idx'),
        ),
    ]
