# Generated by Django 6.0.6 on 2026-09-16 09:53

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Only common.Workspace is referenced, and it exists from 0001_initial.
        # Pinning to the earliest possible migration keeps this app installable
        # against server submodule versions that do not carry the later common
        # migrations yet.
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='The provider session token the client sent with these requests.', max_length=64, verbose_name='Session Token')),
                ('request_count', models.PositiveIntegerField(default=0, help_text='Autocomplete requests made in this session, billable only if it is abandoned.', verbose_name='Autocomplete Requests')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('last_request_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this session was last used; how an abandoned session is recognised.', verbose_name='Last Request At')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_autocomplete_sessions', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Autocomplete Session',
                'verbose_name_plural': 'Autocomplete Sessions',
                'ordering': ['-last_request_at'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['workspace', 'last_request_at'], name='geo_autocom_workspa_64458e_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'token'), name='geo_autocomplete_session_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
