# Generated by Django 5.1.3 on 2026-03-28 23:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_settings_default_currency'),
        ('shop', '0003_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('region', models.CharField(choices=[('us', 'United States'), ('eu', 'Europe'), ('apac', 'Asia Pacific')], max_length=20, verbose_name='Region')),
                ('api_base_url', models.URLField(verbose_name='API Base URL')),
                ('db_host', models.CharField(max_length=255, verbose_name='DB Host')),
                ('db_port', models.IntegerField(default=3306, verbose_name='DB Port')),
                ('redis_url', models.URLField(verbose_name='Redis URL')),
                ('s3_bucket', models.CharField(max_length=255, verbose_name='S3 Bucket')),
                ('max_workspaces', models.IntegerField(default=500, verbose_name='Max Workspaces')),
                ('current_workspaces', models.IntegerField(default=0, verbose_name='Current Workspaces')),
                ('is_accepting_new', models.BooleanField(default=True, verbose_name='Accepting New Workspaces')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Last Health Check')),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='unknown', max_length=20, verbose_name='Health Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('shop', 'Shop'), ('marketing', 'Marketing'), ('ai', 'AI'), ('support', 'Support'), ('finance', 'Finance'), ('web', 'Web'), ('core', 'Core')], max_length=50, verbose_name='Category')),
                ('default_enabled', models.BooleanField(default=False, verbose_name='Default Enabled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('min_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_features', to='shop.subscriptionplan', verbose_name='Minimum Plan')),
            ],
            options={
                'verbose_name': 'Feature Definition',
                'verbose_name_plural': 'Feature Definitions',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WorkspacePlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='us', max_length=20, verbose_name='Region')),
                ('platform_api_key', models.CharField(blank=True, max_length=64, verbose_name='Platform API Key')),
                ('agent_api_key', models.CharField(blank=True, max_length=64, verbose_name='Agent API Key')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspended At')),
                ('scheduled_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Deletion At')),
                ('custom_domain', models.CharField(blank=True, max_length=255, verbose_name='Custom Domain')),
                ('ssl_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='none', max_length=20, verbose_name='SSL Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='platform.cluster', verbose_name='Cluster')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace Platform Profile',
                'verbose_name_plural': 'Workspace Platform Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('suspend', 'Suspend'), ('resume', 'Resume'), ('migrate', 'Migrate'), ('delete', 'Delete')], max_length=50, verbose_name='Operation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_operations', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace Operation',
                'verbose_name_plural': 'Workspace Operations',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workspace', '-started_at'], name='platform_wo_workspa_1f9ac2_idx'), models.Index(fields=['status'], name='platform_wo_status_01ade5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(max_length=100, unique=True, verbose_name='Email Domain')),
                ('protocol', models.CharField(choices=[('google_oauth2', 'Google Workspace OAuth2'), ('azure_oidc', 'Azure AD / Entra ID OIDC'), ('saml2', 'Generic SAML 2.0'), ('oidc', 'Generic OIDC')], max_length=20, verbose_name='Protocol')),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=200, verbose_name='Client Secret')),
                ('tenant_id', models.CharField(blank=True, max_length=100, verbose_name='Tenant ID')),
                ('saml_metadata_url', models.URLField(blank=True, verbose_name='SAML Metadata URL')),
                ('oidc_discovery_url', models.URLField(blank=True, verbose_name='OIDC Discovery URL')),
                ('default_role', models.CharField(default='staff', max_length=50, verbose_name='Default Role')),
                ('role_mapping', models.JSONField(blank=True, default=dict, verbose_name='Role Mapping')),
                ('enforce_sso', models.BooleanField(default=False, verbose_name='Enforce SSO')),
                ('auto_provision', models.BooleanField(default=True, verbose_name='Auto Provision')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_configs', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace SSO Config',
                'verbose_name_plural': 'Workspace SSO Configs',
                'ordering': ['email_domain'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='platform_wo_workspa_55e3c5_idx')],
            },
        ),
    ]
