# Generated by Django 5.1.3 on 2026-03-30 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceplatformprofile',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspaceplatformprofile',
            name='remote_workspace_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of the workspace on the remote cluster/workspace instance', null=True, verbose_name='Remote Workspace UUID'),
        ),
        migrations.CreateModel(
            name='PlatformMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='platform.workspaceplatformprofile', verbose_name='Workspace Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Platform Membership',
                'verbose_name_plural': 'Platform Memberships',
                'indexes': [models.Index(fields=['user', 'is_active'], name='platform_pl_user_id_9b771b_idx'), models.Index(fields=['profile', 'is_active'], name='platform_pl_profile_9a44fd_idx')],
                'unique_together': {('user', 'profile')},
            },
        ),
    ]
