# Generated by Django 5.1.3 on 2026-03-30 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_platform_user_id'),
        ('platform', '0002_remove_workspaceplatformprofile_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceplatformprofile',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to='common.workspace', verbose_name='Workspace'),
        ),
    ]
