# Generated by Django 5.1.3 on 2026-04-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_add_workspace_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='frontend_base_url',
            field=models.URLField(blank=True, default='', verbose_name='Frontend Base URL'),
        ),
    ]
