# Generated by Django 6.0.6 on 2026-09-16 09:21

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Make a partially applied MySQL migration safe to retry."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        with schema_editor.connection.cursor() as cursor:
            columns = schema_editor.connection.introspection.get_table_description(
                cursor, model._meta.db_table
            )
        if model._meta.get_field(self.name).column not in {column.name for column in columns}:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class CreateModelIfMissing(migrations.CreateModel):
    """Skip a model table already created before a release was interrupted."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table not in schema_editor.connection.introspection.table_names():
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_workspace_extension'),
        ('platform', '0006_remove_profile_domain_fields'),
        ('shop', '0010_return_number_per_workspace_and_times'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddFieldIfMissing(
            model_name='workspaceplatformprofile',
            name='monthly_usage_cap_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Usage Cap (points)'),
        ),
        CreateModelIfMissing(
            name='MeterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=100, verbose_name='Meter')),
                ('vendor_cost', models.DecimalField(decimal_places=6, help_text='What the vendor charges for one unit_size of this meter.', max_digits=12, verbose_name='Vendor Cost (USD)')),
                ('unit_size', models.PositiveIntegerField(default=1, help_text='How many calls or tokens the vendor cost buys.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unit Size')),
                ('margin', models.DecimalField(blank=True, decimal_places=4, help_text='Share added on top of the vendor cost; empty uses the platform default.', max_digits=6, null=True, verbose_name='Margin')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective From')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Meter Price',
                'verbose_name_plural': 'Meter Prices',
                'ordering': ['meter', '-effective_from'],
                'indexes': [models.Index(fields=['meter', '-effective_from'], name='platform_me_meter_b62935_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_size__gt', 0)), name='platform_meter_price_unit_size_positive')],
            },
        ),
        CreateModelIfMissing(
            name='PlatformVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Key')),
                ('value', models.JSONField(verbose_name='Value')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Platform Variable',
                'verbose_name_plural': 'Platform Variables',
                'ordering': ['key'],
            },
        ),
        CreateModelIfMissing(
            name='PlatformVariableChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.JSONField(verbose_name='New Value')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Changed At')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='platform.platformvariable', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Platform Variable Change',
                'verbose_name_plural': 'Platform Variable Changes',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['variable', '-changed_at'], name='platform_pl_variabl_b6c786_idx')],
            },
        ),
        CreateModelIfMissing(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=100, verbose_name='Meter')),
                ('day', models.DateField(verbose_name='Day (UTC)')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='Quantity')),
                ('points', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=16, verbose_name='Points')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='platform.meterprice', verbose_name='Price')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'ordering': ['-day', 'meter'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['workspace', 'day'], name='platform_us_workspa_ec916e_idx'), models.Index(fields=['meter', 'day'], name='platform_us_meter_5f58ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'meter', 'day', 'price'), name='platform_usage_record_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfMissing(
            name='WorkspaceEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, verbose_name='Key')),
                ('source', models.CharField(choices=[('purchased', 'Purchased'), ('granted', 'Granted')], default='purchased', max_length=16, verbose_name='Source')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starts At')),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Empty never expires.', null=True, verbose_name='Current Period End')),
                ('grace_until', models.DateTimeField(blank=True, null=True, verbose_name='Grace Until')),
                ('status', models.CharField(choices=[('active', 'Active'), ('grace', 'Grace'), ('ended', 'Ended')], default='active', max_length=16, verbose_name='Status')),
                ('reason', models.CharField(blank=True, help_text='Why the entitlement exists, for one that was granted.', max_length=255, verbose_name='Reason')),
                ('ended_reason', models.CharField(blank=True, max_length=255, verbose_name='Ended Reason')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(blank=True, help_text='Empty for an entitlement that was granted rather than bought.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='shop.subscriptionplan', verbose_name='Plan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace Entitlement',
                'verbose_name_plural': 'Workspace Entitlements',
                'ordering': ['key', '-starts_at'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['workspace', 'key', 'status'], name='platform_wo_workspa_a8bda7_idx'), models.Index(fields=['status', 'current_period_end'], name='platform_wo_status_8eb4bf_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
