# Generated by Django 6.0.6 on 2026-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_workspace_extension'),
        ('platform', '0007_usage_and_entitlements'),
        ('shop', '0010_return_number_per_workspace_and_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceplatformprofile',
            name='trial_points_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial Credit Used At'),
        ),
        migrations.AddIndex(
            model_name='workspaceentitlement',
            index=models.Index(fields=['current_period_end'], name='platform_wo_current_ae7a4a_idx'),
        ),
    ]
