# Generated by Django 6.0.6 on 2026-09-20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Skip a model table already created before a release was interrupted."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table not in schema_editor.connection.introspection.table_names():
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0008_trial_credit_and_period_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfMissing(
            name="PlatformAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=500)),
                ("result", models.CharField(default="succeeded", max_length=32)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="platform_control_audit_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["target_type", "target_id", "-created_at"], name="plat_ctrl_audit_target_idx"),
                    models.Index(fields=["action", "-created_at"], name="plat_ctrl_audit_action_idx"),
                    models.Index(fields=["actor", "-created_at"], name="plat_ctrl_audit_actor_idx"),
                ],
            },
        ),
        CreateModelIfMissing(
            name="PlatformControlActionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=128)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=255)),
                ("payload_hash", models.CharField(max_length=64)),
                ("result", models.CharField(choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="pending", max_length=20)),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_control_action_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(fields=("created_by", "idempotency_key"), name="platform_control_request_key"),
                ],
            },
        ),
    ]
