# Generated by Django 5.1.6 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0009_platform_control_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="config_version",
            field=models.PositiveIntegerField(default=1, verbose_name="Configuration Version"),
        ),
    ]
