# Generated by Django 5.1 on 2026-09-20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0009_platform_console_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceMeterUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meter", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("units", models.DecimalField(decimal_places=4, max_digits=20)),
                ("points", models.DecimalField(decimal_places=4, max_digits=20)),
                ("period_start", models.DateField(db_index=True)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("price", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="usage_records", to="platform.platformmeterprice")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_meter_usage", to="common.workspace")),
            ],
            options={"ordering": ["-recorded_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="workspacemeterusage",
            constraint=models.UniqueConstraint(fields=("workspace", "meter", "idempotency_key"), name="platform_meter_usage_idempotency"),
        ),
        migrations.AddIndex(
            model_name="workspacemeterusage",
            index=models.Index(fields=["workspace", "meter", "period_start"], name="platform_meter_usage_period"),
        ),
    ]
