# Generated by Django 5.1.6 on 2026-09-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0010_cluster_config_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterHealthObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("health_status", models.CharField(max_length=20)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(choices=[("checked", "Checked"), ("configuration_unavailable", "Configuration unavailable"), ("configuration_changed", "Configuration changed")], default="checked", max_length=32)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="health_observations", to="platform.cluster")),
                ("observed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cluster_health_observations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-observed_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="clusterhealthobservation",
            index=models.Index(fields=["cluster", "-observed_at"], name="plat_cluster_health_obs_idx"),
        ),
    ]
