# Generated by Django 5.1.6 on 2026-09-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class CreateModelIfMissing(migrations.CreateModel):
    """Skip a model table already created before a release was interrupted."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table not in schema_editor.connection.introspection.table_names():
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfMissing(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        with schema_editor.connection.cursor() as cursor:
            indexes = schema_editor.connection.introspection.get_constraints(cursor, model._meta.db_table)
        if self.index.name not in indexes:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0010_cluster_config_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfMissing(
            name="ClusterHealthObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("health_status", models.CharField(max_length=20)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(choices=[("checked", "Checked"), ("configuration_unavailable", "Configuration unavailable"), ("configuration_changed", "Configuration changed")], default="checked", max_length=32)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("cluster", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="health_observations", to="platform.cluster")),
                ("observed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cluster_health_observations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-observed_at", "-id"]},
        ),
        AddIndexIfMissing(
            model_name="clusterhealthobservation",
            index=models.Index(fields=["cluster", "-observed_at"], name="plat_cluster_health_obs_idx"),
        ),
    ]
