# Generated by Django 5.1.6 on 2026-09-20

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0011_cluster_health_observation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceplatformprofile",
            name="placement_fence",
            field=models.PositiveIntegerField(default=0, verbose_name="Placement Fence"),
        ),
        migrations.CreateModel(
            name="WorkspacePlacementRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("profile_fence", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("reserved", "Capacity reserved"), ("rolled_back", "Rolled back"), ("expired", "Expired")], default="reserved", max_length=20)),
                ("reservation_expires_at", models.DateTimeField()),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspace_placement_requests", to=settings.AUTH_USER_MODEL)),
                ("source_cluster", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="placement_requests_from", to="platform.cluster")),
                ("target_cluster", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="placement_requests_to", to="platform.cluster")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="placement_requests", to="common.workspace")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="WorkspacePlacementEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=40)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="platform.workspaceplacementrequest")),
            ],
            options={"ordering": ["sequence", "id"]},
        ),
        migrations.AddIndex(
            model_name="workspaceplacementrequest",
            index=models.Index(fields=["target_cluster", "status", "reservation_expires_at"], name="plat_place_target_idx"),
        ),
        migrations.AddIndex(
            model_name="workspaceplacementrequest",
            index=models.Index(fields=["workspace", "status", "-created_at"], name="plat_place_workspace_idx"),
        ),
        migrations.AddConstraint(
            model_name="workspaceplacementrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "reserved")), fields=("workspace",), name="plat_place_one_active_per_workspace"),
        ),
        migrations.AddConstraint(
            model_name="workspaceplacementevent",
            constraint=models.UniqueConstraint(fields=("request", "sequence"), name="plat_place_event_sequence"),
        ),
    ]
