# Generated by Django 6.0.6 on 2026-06-11 14:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_booking_status_alter_inquiry_inquiry_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelManagers(
            name='site',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
