# Generated by Django 5.1.3 on 2026-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Default Currency'),
        ),
    ]
