# Generated by Django 5.1.3 on 2026-03-23 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_settings_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label for this key, e.g. 'Shopify sync'.", max_length=255, verbose_name='Name')),
                ('prefix', models.CharField(db_index=True, editable=False, help_text="Public prefix used for lookup (displayed as the 'API Key').", max_length=16, unique=True, verbose_name='Key Prefix')),
                ('secret_hash', models.CharField(editable=False, help_text='SHA-256 hash of the secret. The raw secret is never stored.', max_length=64, verbose_name='Secret Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date. Null means never expires.', null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='common_apik_workspa_526063_idx')],
            },
        ),
    ]
