# Generated by Django 5.1.3 on 2026-03-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_apikey_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Mapping identifier towards the central BFG Platform SSO', max_length=255, null=True, unique=True, verbose_name='Platform User ID'),
        ),
    ]
