# Generated by Django 6.0.6 on 2026-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_address_options_alter_apikey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_sensitive',
            field=models.BooleanField(default=False, verbose_name='Sensitive'),
        ),
    ]
