# Generated by Django 6.0.6 on 2026-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_settings_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
    ]
