# Generated by Django 6.0.6 on 2026-09-05 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], max_length=30, verbose_name='Provider')),
                ('client_id', models.CharField(help_text='OAuth client ID / App ID. Public — the browser needs it.', max_length=191, verbose_name='Client ID')),
                ('secret', models.CharField(blank=True, max_length=191, verbose_name='Client Secret')),
                ('key', models.CharField(blank=True, max_length=191, verbose_name='Key')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Extra Settings')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workspace', models.ForeignKey(blank=True, help_text='Empty means the platform default, inherited by every workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_auth_configs', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Social Auth Config',
                'verbose_name_plural': 'Social Auth Configs',
                'ordering': ['provider'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='common_soci_workspa_a0e0be_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider'), name='uniq_social_auth_config_workspace_provider'), models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('provider',), name='uniq_social_auth_config_platform_provider')],
            },
        ),
    ]
