# Generated by Django 6.0.6 on 2026-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_seed_platform_social_auth_from_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enabled_currencies',
            field=models.JSONField(blank=True, default=list, verbose_name='Enabled Currencies'),
        ),
    ]
