# Generated by Django 6.0.6 on 2026-09-13 07:46

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_settings_enabled_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Extension')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('archiving', 'Archiving'), ('archived', 'Archived'), ('restoring', 'Restoring')], default='active', max_length=16, verbose_name='Status')),
                ('status_reason', models.CharField(blank=True, max_length=64, verbose_name='Status reason')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status changed at')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last activated at')),
                ('archive_location', models.CharField(blank=True, max_length=512, verbose_name='Archive location')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Status changed by')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_records', to='common.workspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Workspace extension',
                'verbose_name_plural': 'Workspace extensions',
                'ordering': ['key'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['key', 'status'], name='common_work_key_055564_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'key'), name='common_workspace_extension_uniq')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
